-- Larry Documents: files generated by Larry (email drafts, letters, memos, reports)
CREATE TABLE IF NOT EXISTS larry_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  project_id UUID REFERENCES projects(id) ON DELETE SET NULL,
  larry_event_id UUID REFERENCES larry_events(id) ON DELETE SET NULL,

  title TEXT NOT NULL,
  doc_type TEXT NOT NULL CHECK (doc_type IN ('email_draft', 'letter', 'memo', 'report', 'note', 'other')),
  content TEXT NOT NULL,

  email_recipient TEXT,
  email_subject TEXT,
  email_sent_at TIMESTAMPTZ,

  state TEXT NOT NULL DEFAULT 'draft' CHECK (state IN ('draft', 'final', 'sent')),

  created_by_user_id UUID REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_larry_documents_tenant ON larry_documents(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_larry_documents_project ON larry_documents(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_larry_documents_event ON larry_documents(larry_event_id);

ALTER TABLE larry_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY larry_documents_tenant_isolation ON larry_documents
  USING (tenant_id = current_setting('app.current_tenant_id')::uuid);
