import { FastifyPluginAsync } from "fastify";
import { authRoutes } from "./auth.js";
import { projectRoutes } from "./projects.js";
import { taskRoutes } from "./tasks.js";
import { categoryRoutes } from "./categories.js";
import { ingestRoutes } from "./ingest.js";
import { reportingRoutes } from "./reporting.js";
import { slackConnectorRoutes } from "./connectors-slack.js";
import { googleCalendarConnectorRoutes } from "./connectors-google-calendar.js";
import { outlookCalendarConnectorRoutes } from "./connectors-outlook-calendar.js";
import { larryRoutes } from "./larry.js";
import { larryDocumentsRoutes } from "./larry-documents.js";
import { emailConnectorRoutes } from "./connectors-email.js";
import { activityRoutes } from "./activity.js";
import { notificationRoutes } from "./notifications.js";
import { meetingRoutes } from "./meetings.js";
import { orgRoutes } from "./orgs.js";
import { projectIntakeRoutes } from "./project-intake.js";
import { documentRoutes } from "./documents.js";
import { folderRoutes } from "./folders.js";
import { settingsRoutes } from "./settings.js";
import { searchRoutes } from "./search.js";
import { adminRoutes } from "./admin.js";
import { resendWebhookRoutes } from "./webhooks-resend.js";

export const v1Routes: FastifyPluginAsync = async (fastify) => {
  await fastify.register(authRoutes, { prefix: "/auth" });
  await fastify.register(projectRoutes, { prefix: "/projects" });
  await fastify.register(projectIntakeRoutes, { prefix: "/projects" });
  await fastify.register(documentRoutes, { prefix: "/documents" });
  await fastify.register(folderRoutes, { prefix: "/folders" });
  await fastify.register(taskRoutes, { prefix: "/tasks" });
  await fastify.register(categoryRoutes, { prefix: "/categories" });
  await fastify.register(ingestRoutes, { prefix: "/ingest" });
  await fastify.register(slackConnectorRoutes, { prefix: "/connectors/slack" });
  await fastify.register(googleCalendarConnectorRoutes, { prefix: "/connectors/google-calendar" });
  await fastify.register(outlookCalendarConnectorRoutes, { prefix: "/connectors/outlook-calendar" });
  await fastify.register(emailConnectorRoutes, { prefix: "/connectors/email" });
  await fastify.register(larryRoutes, { prefix: "/larry" });
  await fastify.register(larryDocumentsRoutes, { prefix: "/larry/documents" });
  await fastify.register(activityRoutes);
  await fastify.register(reportingRoutes);
  await fastify.register(notificationRoutes);
  await fastify.register(meetingRoutes);
  await fastify.register(orgRoutes);
  await fastify.register(settingsRoutes, { prefix: "/settings" });
  await fastify.register(searchRoutes);
  await fastify.register(adminRoutes, { prefix: "/admin" });
  await fastify.register(resendWebhookRoutes, { prefix: "/webhooks" });
};
