"use client";

import Link from "next/link";
import { Activity, CheckCircle2, FolderKanban, Mail, RefreshCw, Sparkles } from "lucide-react";
import type { WorkspaceLarryEvent } from "@/app/dashboard/types";
import { useLarryActionCentre } from "@/hooks/useLarryActionCentre";
import { useEmailDrafts } from "@/hooks/useEmailDrafts";

export const dynamic = "force-dynamic";

function formatDate(value?: string | null): string {
  if (!value) return "No date set";
  return new Date(value).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function formatRelativeTime(value?: string | null): string {
  if (!value) return "Just now";
  const delta = Date.now() - new Date(value).getTime();
  const minutes = Math.max(0, Math.floor(delta / 60_000));
  if (minutes < 1) return "Just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d ago`;
  return formatDate(value);
}

function formatStatus(value?: string | null): string {
  if (!value) return "Unknown";
  return value.replace(/[_-]+/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

function getEventTone(event: WorkspaceLarryEvent) {
  if (event.eventType === "suggested") {
    return { background: "#fff7ed", color: "#c2410c", border: "#fdba74", label: "Pending approval" };
  }
  if (event.eventType === "accepted") {
    return { background: "#ecfdf3", color: "#15803d", border: "#bbf7d0", label: "Accepted" };
  }
  return { background: "#eff6ff", color: "#1d4ed8", border: "#bfdbfe", label: "Auto executed" };
}

function getEventOriginLabel(sourceKind?: string | null): string {
  switch (sourceKind) {
    case "meeting":
      return "Meeting transcript";
    case "briefing":
      return "Login briefing";
    case "schedule":
      return "Scheduled scan";
    case "slack":
      return "Slack signal";
    case "email":
      return "Email signal";
    case "calendar":
      return "Calendar signal";
    case "chat":
    case null:
    case undefined:
      return "Larry chat";
    default:
      return formatStatus(sourceKind);
  }
}

function getEventSourceMeta(sourceKind?: string | null): string {
  switch (sourceKind) {
    case "meeting":
      return "Captured from meeting transcript";
    case "briefing":
      return "Generated during login briefing";
    case "schedule":
      return "Generated by scheduled scan";
    case "slack":
      return "Generated from Slack signal";
    case "email":
      return "Generated from email signal";
    case "calendar":
      return "Generated from calendar signal";
    case "chat":
    case null:
    case undefined:
      return "Requested from Larry chat";
    default:
      return `Generated from ${formatStatus(sourceKind)}`;
  }
}

function getEventMeta(event: WorkspaceLarryEvent): string {
  const pieces = [
    formatStatus(event.actionType),
    event.requestedByName ? `Requested by ${event.requestedByName}` : getEventSourceMeta(event.sourceKind),
  ];

  if (event.eventType === "accepted" && event.approvedByName) {
    pieces.push(`Accepted by ${event.approvedByName}`);
  } else if (event.executionMode === "auto") {
    pieces.push("Executed by Larry");
  } else if (event.executedByName) {
    pieces.push(`Executed by ${event.executedByName}`);
  }

  return pieces.join(" | ");
}

function getProjectLabel(event: WorkspaceLarryEvent): string {
  return event.projectName?.trim() || "Project";
}

function openConversation(event: WorkspaceLarryEvent) {
  if (!event.conversationId) return;
  window.dispatchEvent(new CustomEvent("larry:open"));
  window.dispatchEvent(new CustomEvent("larry:load-conversation", { detail: event.conversationId }));
}

function buildLinkedChatHref(event: WorkspaceLarryEvent): string | null {
  if (!event.conversationId) return null;

  const params = new URLSearchParams({
    projectId: event.projectId,
    conversationId: event.conversationId,
    launch: "action-centre",
    sourceKind: event.sourceKind ?? "chat",
    eventType: event.eventType,
  });

  return `/workspace/chats?${params.toString()}`;
}

function ProjectBadge({ event }: { event: WorkspaceLarryEvent }) {
  return (
    <Link
      href={`/workspace/projects/${event.projectId}`}
      className="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[12px] font-semibold"
      style={{
        borderColor: "var(--border)",
        background: "var(--surface)",
        color: "var(--text-2)",
      }}
    >
      <FolderKanban size={14} />
      {getProjectLabel(event)}
    </Link>
  );
}

export default function WorkspaceActionsPage() {
  const {
    suggested,
    activity,
    conversations,
    loading,
    error,
    accepting,
    dismissing,
    accept,
    dismiss,
    refresh,
  } = useLarryActionCentre();

  const { drafts: emailDrafts, sending: sendingDraft, send: sendDraft, dismiss: dismissDraft } = useEmailDrafts();

  const projectsTouched = new Set([...suggested, ...activity].map((event) => event.projectId)).size;
  const linkedConversationCount = new Set(
    [...suggested, ...activity].map((event) => event.conversationId).filter(Boolean)
  ).size;

  return (
    <div className="min-h-0 flex-1 overflow-y-auto" style={{ background: "var(--page-bg)" }}>
      <div className="mx-auto max-w-[1200px] space-y-6 px-6 py-8">
        <section
          style={{
            borderRadius: "var(--radius-card)",
            border: "1px solid var(--border)",
            background: "var(--surface)",
            padding: "24px",
          }}
        >
          <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
            <div className="min-w-0 flex-1">
              <div
                className="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[12px] font-semibold"
                style={{ borderColor: "var(--border)", color: "var(--text-2)", background: "var(--surface-2)" }}
              >
                <Sparkles size={14} />
                Tenant-wide Larry ledger
              </div>
              <h1 className="mt-4 text-[28px] font-semibold tracking-[-0.04em]" style={{ color: "var(--text-1)" }}>
                Workspace Action Centre
              </h1>
              <p className="mt-3 max-w-[760px] text-[15px] leading-7" style={{ color: "var(--text-2)" }}>
                Review Larry actions across projects from the same canonical ledger the project workspaces already use.
                Accept or dismiss suggestions here, then jump straight into the linked project or chat when you need more context.
              </p>
            </div>
            <div className="flex flex-wrap gap-3">
              <button
                type="button"
                onClick={() => {
                  void refresh();
                }}
                className="inline-flex h-10 items-center gap-2 rounded-full border px-4 text-[13px] font-semibold"
                style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
              >
                <RefreshCw size={14} />
                Refresh
              </button>
              <Link
                href="/workspace/chats"
                className="inline-flex h-10 items-center gap-2 rounded-full px-4 text-[13px] font-semibold text-white"
                style={{ background: "var(--cta)" }}
              >
                <Sparkles size={14} />
                Open Larry chats
              </Link>
            </div>
          </div>
        </section>

        <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          {[
            { label: "Pending review", value: String(suggested.length), detail: "Awaiting approval" },
            { label: "Recent activity", value: String(activity.length), detail: "Accepted or auto executed" },
            { label: "Projects touched", value: String(projectsTouched), detail: "Cross-project visibility" },
            { label: "Linked chats", value: String(linkedConversationCount || conversations.length), detail: "Jump back into context" },
          ].map((stat) => (
            <div
              key={stat.label}
              style={{
                borderRadius: "var(--radius-card)",
                border: "1px solid var(--border)",
                background: "var(--surface)",
                padding: "18px 20px",
              }}
            >
              <p className="text-[12px] font-semibold uppercase tracking-[0.14em]" style={{ color: "var(--text-muted)" }}>
                {stat.label}
              </p>
              <p className="mt-3 text-[28px] font-semibold tracking-[-0.04em]" style={{ color: "var(--text-1)" }}>
                {stat.value}
              </p>
              <p className="mt-2 text-[13px]" style={{ color: "var(--text-2)" }}>
                {stat.detail}
              </p>
            </div>
          ))}
        </section>

        {emailDrafts.length > 0 && (
          <section
            style={{
              borderRadius: "var(--radius-card)",
              border: "1px solid var(--border)",
              background: "var(--surface)",
              padding: "20px",
            }}
          >
            <div className="flex items-center gap-3">
              <Mail size={18} style={{ color: "var(--cta)" }} />
              <div>
                <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                  Email drafts
                </p>
                <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                  Larry has prepared these emails for your review.
                </p>
              </div>
            </div>
            <div className="mt-4 space-y-3">
              {emailDrafts.map((draft) => (
                <div
                  key={draft.id}
                  className="rounded-xl border px-4 py-4"
                  style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                >
                  <p className="text-[13px] font-semibold" style={{ color: "var(--text-1)" }}>
                    To: {draft.recipient}
                  </p>
                  <p className="text-[14px] font-semibold mt-1" style={{ color: "var(--text-1)" }}>
                    {draft.subject}
                  </p>
                  <p className="mt-2 text-[13px] leading-6 line-clamp-3" style={{ color: "var(--text-2)" }}>
                    {draft.body}
                  </p>
                  <div className="mt-3 flex items-center gap-2">
                    <button
                      type="button"
                      onClick={() => void dismissDraft(draft.id)}
                      className="rounded-lg border px-3 py-1.5 text-[12px] font-semibold"
                      style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
                    >
                      Dismiss
                    </button>
                    <button
                      type="button"
                      onClick={() => void sendDraft(draft.id)}
                      disabled={sendingDraft === draft.id}
                      className="rounded-lg px-3 py-1.5 text-[12px] font-semibold text-white"
                      style={{ background: "var(--cta)" }}
                    >
                      {sendingDraft === draft.id ? "Sending..." : "Approve & Send"}
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {error && (
          <div
            className="rounded-xl border px-4 py-3 text-[13px]"
            style={{ borderColor: "#fecaca", background: "#fef2f2", color: "#b91c1c" }}
          >
            {error}
          </div>
        )}

        <section className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,1fr)]">
          <div
            style={{
              borderRadius: "var(--radius-card)",
              border: "1px solid var(--border)",
              background: "var(--surface)",
              padding: "20px",
            }}
          >
            <div>
              <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                Pending review
              </p>
              <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                Approval-required Larry actions across every project on the workspace path.
              </p>
            </div>

            <div className="mt-5 space-y-3">
              {loading && suggested.length === 0 ? (
                <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                  Loading suggested actions...
                </p>
              ) : suggested.length === 0 ? (
                <div
                  className="rounded-xl border border-dashed px-4 py-6 text-center"
                  style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                >
                  <p className="text-[14px] font-semibold" style={{ color: "var(--text-1)" }}>
                    Nothing waiting for review
                  </p>
                  <p className="mt-2 text-[13px] leading-6" style={{ color: "var(--text-2)" }}>
                    New Larry suggestions will appear here as chat, transcript, briefing, and scheduled-scan activity flows into the ledger.
                  </p>
                </div>
              ) : (
                suggested.map((event) => (
                  <div
                    key={event.id}
                    className="rounded-xl border px-4 py-4"
                    style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                  >
                    <div className="flex flex-wrap items-start justify-between gap-4">
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <ProjectBadge event={event} />
                          <span
                            className="inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold"
                            style={{
                              background: getEventTone(event).background,
                              color: getEventTone(event).color,
                              borderColor: getEventTone(event).border,
                            }}
                          >
                            {getEventTone(event).label}
                          </span>
                        </div>
                        <p className="mt-3 text-[15px] font-semibold" style={{ color: "var(--text-1)" }}>
                          {event.displayText}
                        </p>
                        <p className="mt-2 text-[13px] leading-6" style={{ color: "var(--text-2)" }}>
                          {event.reasoning || "Larry proposed this action from current project context."}
                        </p>
                      </div>
                    </div>

                    <p className="mt-3 text-[12px]" style={{ color: "var(--text-muted)" }}>
                      {getEventMeta(event)} | {formatRelativeTime(event.createdAt)}
                    </p>

                    {(event.responseMessagePreview || event.requestMessagePreview) && (
                      <p
                        className="mt-3 rounded-[14px] border px-3 py-2 text-[12px] leading-5"
                        style={{ borderColor: "var(--border)", background: "var(--surface)" }}
                      >
                        {(event.responseMessagePreview ?? event.requestMessagePreview)?.trim()}
                      </p>
                    )}

                    <div className="mt-4 flex flex-wrap items-center justify-between gap-3">
                      <div className="flex flex-wrap items-center gap-2">
                        <Link
                          href={`/workspace/projects/${event.projectId}`}
                          className="rounded-full border px-3 py-1.5 text-[12px] font-semibold"
                          style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
                        >
                          Open project
                        </Link>
                        {event.conversationId ? (
                          <>
                            <button
                              type="button"
                              onClick={() => openConversation(event)}
                              className="text-[12px] font-semibold"
                              style={{ color: "var(--cta)" }}
                            >
                              Open linked chat
                            </button>
                            <Link
                              href={buildLinkedChatHref(event)!}
                              className="text-[12px] font-semibold"
                              style={{ color: "var(--cta)" }}
                            >
                              Open in chats
                            </Link>
                          </>
                        ) : (
                          <span className="text-[12px]" style={{ color: "var(--text-muted)" }}>
                            Origin: {getEventOriginLabel(event.sourceKind)}
                          </span>
                        )}
                      </div>

                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          onClick={() => {
                            void dismiss(event.id);
                          }}
                          disabled={dismissing === event.id}
                          className="rounded-full border px-3 py-1.5 text-[12px] font-semibold"
                          style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
                        >
                          {dismissing === event.id ? "Dismissing..." : "Dismiss"}
                        </button>
                        <button
                          type="button"
                          onClick={() => {
                            void accept(event.id);
                          }}
                          disabled={accepting === event.id}
                          className="rounded-full px-3 py-1.5 text-[12px] font-semibold text-white"
                          style={{ background: "var(--cta)" }}
                        >
                          {accepting === event.id ? "Accepting..." : "Accept"}
                        </button>
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>

          <div
            style={{
              borderRadius: "var(--radius-card)",
              border: "1px solid var(--border)",
              background: "var(--surface)",
              padding: "20px",
            }}
          >
            <div className="flex items-center gap-3">
              <Activity size={18} style={{ color: "var(--cta)" }} />
              <div>
                <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                  Recent activity
                </p>
                <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                  Accepted and auto-executed changes from the same canonical ledger.
                </p>
              </div>
            </div>

            <div className="mt-5 space-y-3">
              {loading && activity.length === 0 ? (
                <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                  Loading recent activity...
                </p>
              ) : activity.length === 0 ? (
                <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                  No recent Larry activity logged yet.
                </p>
              ) : (
                activity.map((event) => (
                  <div
                    key={event.id}
                    className="rounded-xl border px-4 py-4"
                    style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                  >
                    <div className="flex items-start gap-3">
                      <CheckCircle2 size={16} className="mt-0.5 shrink-0" style={{ color: "var(--cta)" }} />
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <ProjectBadge event={event} />
                          <span
                            className="inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold"
                            style={{
                              background: getEventTone(event).background,
                              color: getEventTone(event).color,
                              borderColor: getEventTone(event).border,
                            }}
                          >
                            {getEventTone(event).label}
                          </span>
                        </div>
                        <p className="mt-3 text-[14px] font-semibold" style={{ color: "var(--text-1)" }}>
                          {event.displayText}
                        </p>
                        <p className="mt-1 text-[12px]" style={{ color: "var(--text-muted)" }}>
                          {getEventMeta(event)} | {formatRelativeTime(event.executedAt ?? event.createdAt)}
                        </p>
                        {event.responseMessagePreview && (
                          <p className="mt-2 line-clamp-2 text-[12px] leading-5" style={{ color: "var(--text-2)" }}>
                            {event.responseMessagePreview}
                          </p>
                        )}
                        <div className="mt-3 flex flex-wrap items-center gap-3">
                          <Link
                            href={`/workspace/projects/${event.projectId}`}
                            className="text-[12px] font-semibold"
                            style={{ color: "var(--cta)" }}
                          >
                            Open project
                          </Link>
                          {event.conversationId ? (
                            <>
                              <button
                                type="button"
                                onClick={() => openConversation(event)}
                                className="text-[12px] font-semibold"
                                style={{ color: "var(--cta)" }}
                              >
                                Open linked chat
                              </button>
                              <Link
                                href={buildLinkedChatHref(event)!}
                                className="text-[12px] font-semibold"
                                style={{ color: "var(--cta)" }}
                              >
                                Open in chats
                              </Link>
                            </>
                          ) : (
                            <span className="text-[12px]" style={{ color: "var(--text-muted)" }}>
                              Origin: {getEventOriginLabel(event.sourceKind)}
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
