"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import { Activity, CheckCircle2, FolderKanban, Mail, RefreshCw, Search, Layers } from "lucide-react";
import type { WorkspaceLarryEvent } from "@/app/dashboard/types";
import { useLarryActionCentre } from "@/hooks/useLarryActionCentre";
import { useEmailDrafts } from "@/hooks/useEmailDrafts";
import { getActionTypeTag, getAllActionTypes } from "@/lib/action-types";
import { useToast } from "@/components/toast/ToastContext";

export const dynamic = "force-dynamic";

function formatDate(value?: string | null): string {
  if (!value) return "No date set";
  return new Date(value).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function formatRelativeTime(value?: string | null): string {
  if (!value) return "Just now";
  const delta = Date.now() - new Date(value).getTime();
  const minutes = Math.max(0, Math.floor(delta / 60_000));
  if (minutes < 1) return "Just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d ago`;
  return formatDate(value);
}

function formatStatus(value?: string | null): string {
  if (!value) return "Unknown";
  return value.replace(/[_-]+/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

function getEventTone(event: WorkspaceLarryEvent) {
  if (event.eventType === "suggested") {
    return { background: "#fff7ed", color: "#c2410c", border: "#fdba74", label: "Pending approval" };
  }
  if (event.eventType === "accepted") {
    return { background: "#ecfdf3", color: "#15803d", border: "#bbf7d0", label: "Accepted" };
  }
  return { background: "#eff6ff", color: "#1d4ed8", border: "#bfdbfe", label: "Auto executed" };
}

function getEventOriginLabel(sourceKind?: string | null): string {
  switch (sourceKind) {
    case "meeting":
      return "Meeting transcript";
    case "briefing":
      return "Login briefing";
    case "schedule":
      return "Scheduled scan";
    case "slack":
      return "Slack signal";
    case "email":
      return "Email signal";
    case "calendar":
      return "Calendar signal";
    case "chat":
    case null:
    case undefined:
      return "Larry chat";
    default:
      return formatStatus(sourceKind);
  }
}

function getEventSourceMeta(sourceKind?: string | null): string {
  switch (sourceKind) {
    case "meeting":
      return "Captured from meeting transcript";
    case "briefing":
      return "Generated during login briefing";
    case "schedule":
      return "Generated by scheduled scan";
    case "slack":
      return "Generated from Slack signal";
    case "email":
      return "Generated from email signal";
    case "calendar":
      return "Generated from calendar signal";
    case "chat":
    case null:
    case undefined:
      return "Requested from Larry chat";
    default:
      return `Generated from ${formatStatus(sourceKind)}`;
  }
}

function getEventMeta(event: WorkspaceLarryEvent): string {
  const pieces = [
    formatStatus(event.actionType),
    event.requestedByName ? `Requested by ${event.requestedByName}` : getEventSourceMeta(event.sourceKind),
  ];

  if (event.eventType === "accepted" && event.approvedByName) {
    pieces.push(`Accepted by ${event.approvedByName}`);
  } else if (event.executionMode === "auto") {
    pieces.push("Executed by Larry");
  } else if (event.executedByName) {
    pieces.push(`Executed by ${event.executedByName}`);
  }

  return pieces.join(" | ");
}

function getProjectLabel(event: WorkspaceLarryEvent): string {
  return event.projectName?.trim() || "Project";
}

function openConversation(event: WorkspaceLarryEvent) {
  if (!event.conversationId) return;
  window.dispatchEvent(new CustomEvent("larry:open"));
  window.dispatchEvent(new CustomEvent("larry:load-conversation", { detail: event.conversationId }));
}

function buildLinkedChatHref(event: WorkspaceLarryEvent): string | null {
  if (!event.conversationId) return null;

  const params = new URLSearchParams({
    projectId: event.projectId,
    conversationId: event.conversationId,
    launch: "action-centre",
    sourceKind: event.sourceKind ?? "chat",
    eventType: event.eventType,
  });

  return `/workspace/larry?${params.toString()}`;
}

function ProjectBadge({ event }: { event: WorkspaceLarryEvent }) {
  return (
    <Link
      href={`/workspace/projects/${event.projectId}`}
      className="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[12px] font-semibold"
      style={{
        borderColor: "var(--border)",
        background: "var(--surface)",
        color: "var(--text-2)",
      }}
    >
      <FolderKanban size={14} />
      {getProjectLabel(event)}
    </Link>
  );
}

function ActionTypeBadge({ actionType }: { actionType: string }) {
  const tag = getActionTypeTag(actionType);
  return (
    <span
      className="inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-semibold"
      style={{
        background: `${tag.color}18`,
        color: tag.color,
        border: `1px solid ${tag.color}30`,
      }}
    >
      {tag.label}
    </span>
  );
}

const SELECT_STYLE: React.CSSProperties = {
  height: "36px",
  padding: "0 10px",
  borderRadius: "var(--radius-btn, 8px)",
  border: "1px solid var(--border)",
  background: "var(--surface-2)",
  color: "var(--text-1)",
  fontSize: "13px",
  cursor: "pointer",
  outline: "none",
};

type SortOrder = "newest" | "oldest" | "action_type_az";

function matchesSearch(event: WorkspaceLarryEvent, q: string): boolean {
  const lower = q.toLowerCase();
  return (
    event.displayText.toLowerCase().includes(lower) ||
    (event.reasoning ?? "").toLowerCase().includes(lower) ||
    (event.projectName ?? "").toLowerCase().includes(lower) ||
    (event.actionType ?? "").toLowerCase().includes(lower)
  );
}

function applyFilters(
  events: WorkspaceLarryEvent[],
  search: string,
  filterActionType: string,
  filterProjectId: string,
  sortOrder: SortOrder,
): WorkspaceLarryEvent[] {
  let result = events;
  if (search.trim()) result = result.filter((e) => matchesSearch(e, search.trim()));
  if (filterActionType) result = result.filter((e) => e.actionType === filterActionType);
  if (filterProjectId) result = result.filter((e) => e.projectId === filterProjectId);
  return [...result].sort((a, b) => {
    if (sortOrder === "action_type_az") return (a.actionType ?? "").localeCompare(b.actionType ?? "");
    const da = new Date(a.createdAt).getTime();
    const db = new Date(b.createdAt).getTime();
    return sortOrder === "newest" ? db - da : da - db;
  });
}

export default function WorkspaceActionsPage() {
  const { pushToast } = useToast();

  const {
    suggested,
    activity,
    conversations,
    loading,
    error,
    accepting,
    dismissing,
    modifying,
    executing,
    actionError,
    accept,
    dismiss,
    modify,
    letLarryExecute,
    clearActionError,
    refresh,
  } = useLarryActionCentre({
    onAccepted: (toast) => pushToast(toast),
  });

  const { drafts: emailDrafts, sending: sendingDraft, send: sendDraft, dismiss: dismissDraft } = useEmailDrafts();

  // Toolbar state
  const [search, setSearch] = useState("");
  const [filterActionType, setFilterActionType] = useState("");
  const [filterProjectId, setFilterProjectId] = useState("");
  const [sortOrder, setSortOrder] = useState<SortOrder>("newest");

  // Stats always use the raw unfiltered arrays
  const projectsTouched = new Set([...suggested, ...activity].map((event) => event.projectId)).size;
  const linkedConversationCount = new Set(
    [...suggested, ...activity].map((event) => event.conversationId).filter(Boolean)
  ).size;

  // Unique projects for the project dropdown
  const projectOptions = useMemo(() => {
    const map = new Map<string, string>();
    for (const e of [...suggested, ...activity]) {
      if (!map.has(e.projectId)) {
        map.set(e.projectId, e.projectName?.trim() || e.projectId.slice(0, 8));
      }
    }
    return Array.from(map.entries()).sort((a, b) => a[1].localeCompare(b[1]));
  }, [suggested, activity]);

  // Filtered + sorted lists
  const filteredSuggested = useMemo(
    () => applyFilters(suggested, search, filterActionType, filterProjectId, sortOrder),
    [suggested, search, filterActionType, filterProjectId, sortOrder],
  );
  const filteredActivity = useMemo(
    () => applyFilters(activity, search, filterActionType, filterProjectId, sortOrder),
    [activity, search, filterActionType, filterProjectId, sortOrder],
  );

  const hasFilters = search.trim() !== "" || filterActionType !== "" || filterProjectId !== "";

  function clearFilters() {
    setSearch("");
    setFilterActionType("");
    setFilterProjectId("");
    setSortOrder("newest");
  }

  return (
    <div className="min-h-0 flex-1 overflow-y-auto" style={{ background: "var(--page-bg)" }}>
      <div className="mx-auto max-w-[1200px] space-y-6 px-6 py-8">
        <section
          style={{
            borderRadius: "var(--radius-card)",
            border: "1px solid var(--border)",
            background: "var(--surface)",
            padding: "24px",
          }}
        >
          <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
            <div className="min-w-0 flex-1">
              <div
                className="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[12px] font-semibold"
                style={{ borderColor: "var(--border)", color: "var(--text-2)", background: "var(--surface-2)" }}
              >
                <Layers size={14} />
                Tenant-wide Larry ledger
              </div>
              <h1 className="mt-4 text-[28px] font-semibold tracking-[-0.04em]" style={{ color: "var(--text-1)" }}>
                Workspace Action Centre
              </h1>
              <p className="mt-3 max-w-[760px] text-[15px] leading-7" style={{ color: "var(--text-2)" }}>
                Review Larry actions across projects from the same canonical ledger the project workspaces already use.
                Accept or dismiss suggestions here, then jump straight into the linked project or chat when you need more context.
              </p>
            </div>
            <div className="flex flex-wrap gap-3">
              <button
                type="button"
                onClick={() => {
                  void refresh();
                }}
                className="inline-flex h-10 items-center gap-2 rounded-full border px-4 text-[13px] font-semibold"
                style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
              >
                <RefreshCw size={14} />
                Refresh
              </button>
              <Link
                href="/workspace/larry"
                className="inline-flex h-10 items-center gap-2 rounded-full px-4 text-[13px] font-semibold text-white"
                style={{ background: "var(--cta)" }}
              >
                <Layers size={14} />
                Open Larry chats
              </Link>
            </div>
          </div>
        </section>

        <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          {[
            { label: "Pending review", value: String(suggested.length), detail: "Awaiting approval" },
            { label: "Recent activity", value: String(activity.length), detail: "Accepted or auto executed" },
            { label: "Projects touched", value: String(projectsTouched), detail: "Cross-project visibility" },
            { label: "Linked chats", value: String(linkedConversationCount || conversations.length), detail: "Jump back into context" },
          ].map((stat) => (
            <div
              key={stat.label}
              style={{
                borderRadius: "var(--radius-card)",
                border: "1px solid var(--border)",
                background: "var(--surface)",
                padding: "18px 20px",
              }}
            >
              <p className="text-[12px] font-semibold uppercase tracking-[0.14em]" style={{ color: "var(--text-muted)" }}>
                {stat.label}
              </p>
              <p className="mt-3 text-[28px] font-semibold tracking-[-0.04em]" style={{ color: "var(--text-1)" }}>
                {stat.value}
              </p>
              <p className="mt-2 text-[13px]" style={{ color: "var(--text-2)" }}>
                {stat.detail}
              </p>
            </div>
          ))}
        </section>

        {/* ── Toolbar ── */}
        <section
          style={{
            borderRadius: "var(--radius-card)",
            border: "1px solid var(--border)",
            background: "var(--surface)",
            padding: "14px 16px",
          }}
        >
          <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", alignItems: "center" }}>
            {/* Search */}
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: "8px",
                height: "36px",
                padding: "0 10px",
                borderRadius: "var(--radius-btn, 8px)",
                border: "1px solid var(--border)",
                background: "var(--surface-2)",
                flex: "1 1 200px",
                maxWidth: "340px",
              }}
            >
              <Search size={13} style={{ color: "var(--text-muted)", flexShrink: 0 }} />
              <input
                placeholder="Search actions…"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                style={{
                  flex: 1,
                  background: "none",
                  border: "none",
                  outline: "none",
                  fontSize: "13px",
                  color: "var(--text-1)",
                }}
              />
            </div>

            {/* Action type filter */}
            <select
              value={filterActionType}
              onChange={(e) => setFilterActionType(e.target.value)}
              style={SELECT_STYLE}
            >
              <option value="">All action types</option>
              {getAllActionTypes().map((tag) => (
                <option key={tag.key} value={tag.key}>{tag.label}</option>
              ))}
            </select>

            {/* Project filter — only shown when there are multiple projects */}
            {projectOptions.length > 1 && (
              <select
                value={filterProjectId}
                onChange={(e) => setFilterProjectId(e.target.value)}
                style={SELECT_STYLE}
              >
                <option value="">All projects</option>
                {projectOptions.map(([id, name]) => (
                  <option key={id} value={id}>{name}</option>
                ))}
              </select>
            )}

            {/* Sort order */}
            <select
              value={sortOrder}
              onChange={(e) => setSortOrder(e.target.value as SortOrder)}
              style={SELECT_STYLE}
            >
              <option value="newest">Newest first</option>
              <option value="oldest">Oldest first</option>
              <option value="action_type_az">Action type A–Z</option>
            </select>

            {/* Clear filters link */}
            {hasFilters && (
              <button
                type="button"
                onClick={clearFilters}
                className="text-[12px] font-semibold"
                style={{ color: "var(--cta)", background: "none", border: "none", cursor: "pointer", whiteSpace: "nowrap" }}
              >
                Clear filters
              </button>
            )}
          </div>
        </section>

        {emailDrafts.length > 0 && (
          <section
            style={{
              borderRadius: "var(--radius-card)",
              border: "1px solid var(--border)",
              background: "var(--surface)",
              padding: "20px",
            }}
          >
            <div className="flex items-center gap-3">
              <Mail size={18} style={{ color: "var(--cta)" }} />
              <div>
                <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                  Email drafts
                </p>
                <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                  Larry has prepared these emails for your review.
                </p>
              </div>
            </div>
            <div className="mt-4 space-y-3">
              {emailDrafts.map((draft) => (
                <div
                  key={draft.id}
                  className="rounded-xl border px-4 py-4"
                  style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                >
                  <p className="text-[13px] font-semibold" style={{ color: "var(--text-1)" }}>
                    To: {draft.recipient}
                  </p>
                  <p className="text-[14px] font-semibold mt-1" style={{ color: "var(--text-1)" }}>
                    {draft.subject}
                  </p>
                  <p className="mt-2 text-[13px] leading-6 line-clamp-3" style={{ color: "var(--text-2)" }}>
                    {draft.body}
                  </p>
                  <div className="mt-3 flex items-center gap-2">
                    <button
                      type="button"
                      onClick={() => void dismissDraft(draft.id)}
                      className="rounded-lg border px-3 py-1.5 text-[12px] font-semibold"
                      style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
                    >
                      Dismiss
                    </button>
                    <button
                      type="button"
                      onClick={() => void sendDraft(draft.id)}
                      disabled={sendingDraft === draft.id}
                      className="rounded-lg px-3 py-1.5 text-[12px] font-semibold text-white"
                      style={{ background: "var(--cta)" }}
                    >
                      {sendingDraft === draft.id ? "Sending..." : "Approve & Send"}
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {error && (
          <div
            className="rounded-xl border px-4 py-3 text-[13px]"
            style={{ borderColor: "#fecaca", background: "#fef2f2", color: "#b91c1c" }}
          >
            {error}
          </div>
        )}

        <section className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,1fr)]">
          <div
            style={{
              borderRadius: "var(--radius-card)",
              border: "1px solid var(--border)",
              background: "var(--surface)",
              padding: "20px",
            }}
          >
            <div>
              <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                Pending review
              </p>
              <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                Approval-required Larry actions across every project on the workspace path.
              </p>
            </div>

            <div className="mt-5 space-y-3">
              {loading && suggested.length === 0 ? (
                <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                  Loading suggested actions...
                </p>
              ) : filteredSuggested.length === 0 ? (
                <div
                  className="rounded-xl border border-dashed px-4 py-6 text-center"
                  style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                >
                  <p className="text-[14px] font-semibold" style={{ color: "var(--text-1)" }}>
                    {hasFilters ? "No suggestions match your filters" : "Nothing waiting for review"}
                  </p>
                  <p className="mt-2 text-[13px] leading-6" style={{ color: "var(--text-2)" }}>
                    {hasFilters
                      ? "Try adjusting your search or filter criteria."
                      : "New Larry suggestions will appear here as chat, transcript, briefing, and scheduled-scan activity flows into the ledger."}
                  </p>
                  {hasFilters && (
                    <button
                      type="button"
                      onClick={clearFilters}
                      className="mt-3 text-[12px] font-semibold"
                      style={{ color: "var(--cta)", background: "none", border: "none", cursor: "pointer" }}
                    >
                      Clear filters
                    </button>
                  )}
                </div>
              ) : (
                filteredSuggested.map((event) => {
                  const canLetLarryDoIt = event.payload?._offerExecution === true;
                  return (
                  <div
                    key={event.id}
                    className="rounded-xl border px-4 py-4"
                    style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                  >
                    <div className="flex flex-wrap items-start justify-between gap-4">
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <ProjectBadge event={event} />
                          <span
                            className="inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold"
                            style={{
                              background: getEventTone(event).background,
                              color: getEventTone(event).color,
                              borderColor: getEventTone(event).border,
                            }}
                          >
                            {getEventTone(event).label}
                          </span>
                          <ActionTypeBadge actionType={event.actionType} />
                        </div>
                        <p className="mt-3 text-[15px] font-semibold" style={{ color: "var(--text-1)" }}>
                          {event.displayText}
                        </p>
                        <p className="mt-2 text-[13px] leading-6" style={{ color: "var(--text-2)" }}>
                          {event.reasoning || "Larry proposed this action from current project context."}
                        </p>
                      </div>
                    </div>

                    <p className="mt-3 text-[12px]" style={{ color: "var(--text-muted)" }}>
                      {getEventMeta(event)} | {formatRelativeTime(event.createdAt)}
                    </p>

                    {(event.responseMessagePreview || event.requestMessagePreview) && (
                      <p
                        className="mt-3 rounded-[14px] border px-3 py-2 text-[12px] leading-5"
                        style={{ borderColor: "var(--border)", background: "var(--surface)" }}
                      >
                        {(event.responseMessagePreview ?? event.requestMessagePreview)?.trim()}
                      </p>
                    )}

                    <div className="mt-4 flex flex-wrap items-center justify-between gap-3">
                      <div className="flex flex-wrap items-center gap-2">
                        <Link
                          href={`/workspace/projects/${event.projectId}`}
                          className="rounded-full border px-3 py-1.5 text-[12px] font-semibold"
                          style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
                        >
                          Open project
                        </Link>
                        {event.conversationId ? (
                          <>
                            <button
                              type="button"
                              onClick={() => openConversation(event)}
                              className="text-[12px] font-semibold"
                              style={{ color: "var(--cta)" }}
                            >
                              Open linked chat
                            </button>
                            <Link
                              href={buildLinkedChatHref(event)!}
                              className="text-[12px] font-semibold"
                              style={{ color: "var(--cta)" }}
                            >
                              Open in chats
                            </Link>
                          </>
                        ) : (
                          <span className="text-[12px]" style={{ color: "var(--text-muted)" }}>
                            Origin: {getEventOriginLabel(event.sourceKind)}
                          </span>
                        )}
                      </div>

                      <div className="flex items-center gap-2">
                        {canLetLarryDoIt && (
                          <button
                            type="button"
                            onClick={() => void letLarryExecute(event.id)}
                            disabled={executing === event.id}
                            className="rounded-full px-3 py-1.5 text-[12px] font-semibold text-white"
                            style={{ background: "var(--cta)" }}
                          >
                            {executing === event.id ? "Working..." : "Let Larry do it"}
                          </button>
                        )}
                        <button
                          type="button"
                          onClick={() => {
                            void dismiss(event.id);
                          }}
                          disabled={dismissing === event.id}
                          className="rounded-full border px-3 py-1.5 text-[12px] font-semibold"
                          style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
                        >
                          {dismissing === event.id ? "Dismissing..." : "Dismiss"}
                        </button>
                        <button
                          type="button"
                          onClick={async () => {
                            const conversationId = await modify(event.id);
                            if (conversationId) {
                              window.dispatchEvent(new CustomEvent("larry:open"));
                              window.dispatchEvent(new CustomEvent("larry:load-conversation", { detail: conversationId }));
                            }
                          }}
                          disabled={modifying === event.id}
                          className="rounded-full border px-3 py-1.5 text-[12px] font-semibold"
                          style={{ borderColor: "var(--cta)", color: "var(--cta)" }}
                        >
                          {modifying === event.id ? "Opening..." : "Modify"}
                        </button>
                        <button
                          type="button"
                          onClick={() => {
                            void accept(event.id);
                          }}
                          disabled={accepting === event.id}
                          className="rounded-full px-3 py-1.5 text-[12px] font-semibold text-white"
                          style={{ background: "var(--cta)" }}
                        >
                          {accepting === event.id ? "Accepting..." : "Accept"}
                        </button>
                      </div>
                    </div>

                    {actionError?.eventId === event.id && (
                      <div
                        className="mt-2 flex items-start justify-between gap-2 rounded-lg px-3 py-2 text-[12px]"
                        style={{ background: "#fef2f2", border: "1px solid #fecaca", color: "#991b1b" }}
                      >
                        <span>{actionError.message}</span>
                        <button
                          type="button"
                          onClick={clearActionError}
                          className="shrink-0 font-semibold hover:underline"
                          style={{ color: "#991b1b" }}
                        >
                          Dismiss
                        </button>
                      </div>
                    )}
                  </div>
                  );
                })
              )}
            </div>
          </div>

          <div
            style={{
              borderRadius: "var(--radius-card)",
              border: "1px solid var(--border)",
              background: "var(--surface)",
              padding: "20px",
            }}
          >
            <div className="flex items-center gap-3">
              <Activity size={18} style={{ color: "var(--cta)" }} />
              <div>
                <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                  Recent activity
                </p>
                <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                  Accepted and auto-executed changes from the same canonical ledger.
                </p>
              </div>
            </div>

            <div className="mt-5 space-y-3">
              {loading && activity.length === 0 ? (
                <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                  Loading recent activity...
                </p>
              ) : filteredActivity.length === 0 ? (
                <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                  {hasFilters ? "No activity matches your filters." : "No recent Larry activity logged yet."}
                </p>
              ) : (
                filteredActivity.map((event) => {
                  const completedByLarry = event.executedByKind === "larry" && event.payload?._selfExecutable === true;
                  return (
                  <div
                    key={event.id}
                    className="rounded-xl border px-4 py-4"
                    style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                  >
                    <div className="flex items-start gap-3">
                      <CheckCircle2 size={16} className="mt-0.5 shrink-0" style={{ color: "var(--cta)" }} />
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <ProjectBadge event={event} />
                          <span
                            className="inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold"
                            style={{
                              background: getEventTone(event).background,
                              color: getEventTone(event).color,
                              borderColor: getEventTone(event).border,
                            }}
                          >
                            {getEventTone(event).label}
                          </span>
                          <ActionTypeBadge actionType={event.actionType} />
                          {completedByLarry && (
                            <span
                              className="inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold"
                              style={{ background: "#ecfdf3", color: "#15803d", borderColor: "#bbf7d0" }}
                            >
                              Completed by Larry
                            </span>
                          )}
                        </div>
                        <p className="mt-3 text-[14px] font-semibold" style={{ color: "var(--text-1)" }}>
                          {event.displayText}
                        </p>
                        <p className="mt-1 text-[12px]" style={{ color: "var(--text-muted)" }}>
                          {getEventMeta(event)} | {formatRelativeTime(event.executedAt ?? event.createdAt)}
                        </p>
                        {event.responseMessagePreview && (
                          <p className="mt-2 line-clamp-2 text-[12px] leading-5" style={{ color: "var(--text-2)" }}>
                            {event.responseMessagePreview}
                          </p>
                        )}
                        <div className="mt-3 flex flex-wrap items-center gap-3">
                          <Link
                            href={`/workspace/projects/${event.projectId}`}
                            className="text-[12px] font-semibold"
                            style={{ color: "var(--cta)" }}
                          >
                            Open project
                          </Link>
                          {event.conversationId ? (
                            <>
                              <button
                                type="button"
                                onClick={() => openConversation(event)}
                                className="text-[12px] font-semibold"
                                style={{ color: "var(--cta)" }}
                              >
                                Open linked chat
                              </button>
                              <Link
                                href={buildLinkedChatHref(event)!}
                                className="text-[12px] font-semibold"
                                style={{ color: "var(--cta)" }}
                              >
                                Open in chats
                              </Link>
                            </>
                          ) : (
                            <span className="text-[12px]" style={{ color: "var(--text-muted)" }}>
                              Origin: {getEventOriginLabel(event.sourceKind)}
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                  );
                })
              )}
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
