"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import {
  Activity,
  ArrowRight,
  CalendarDays,
  CheckCircle2,
  CircleAlert,
  Clock3,
  FolderKanban,
  MessageSquare,
  Sparkles,
} from "lucide-react";
import { useWorkspaceChrome } from "@/app/workspace/WorkspaceChromeContext";
import type {
  WorkspaceConversationPreview,
  WorkspaceLarryEvent,
  WorkspaceProjectMemoryEntry,
} from "@/app/dashboard/types";
import { useProjectData } from "@/hooks/useProjectData";
import { useProjectActionCentre } from "@/hooks/useProjectActionCentre";
import { useProjectMemory } from "@/hooks/useProjectMemory";
import { CollaboratorsPanel } from "./CollaboratorsPanel";

function formatDate(value?: string | null): string {
  if (!value) return "No date set";
  return new Date(value).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function formatRelativeTime(value?: string | null): string {
  if (!value) return "Just now";
  const delta = Date.now() - new Date(value).getTime();
  const minutes = Math.max(0, Math.floor(delta / 60_000));
  if (minutes < 1) return "Just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 7) return `${days}d ago`;
  return formatDate(value);
}

function formatStatus(value?: string | null): string {
  if (!value) return "Unknown";
  return value.replace(/[_-]+/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

function formatPercent(value?: number | null): string {
  if (value == null || Number.isNaN(value)) return "0%";
  return `${Math.round(value)}%`;
}

function getConversationTitle(conversation: WorkspaceConversationPreview): string {
  if (conversation.title?.trim()) return conversation.title.trim();
  if (conversation.lastMessagePreview?.trim()) return conversation.lastMessagePreview.trim().slice(0, 56);
  return "New conversation";
}

function getRiskTone(riskLevel?: string | null) {
  if (riskLevel === "high") {
    return { background: "#fff1f2", color: "#be123c", border: "#fecdd3" };
  }
  if (riskLevel === "medium") {
    return { background: "#fff7ed", color: "#c2410c", border: "#fdba74" };
  }
  return { background: "#eff6ff", color: "#1d4ed8", border: "#bfdbfe" };
}

function getEventTone(event: WorkspaceLarryEvent) {
  if (event.eventType === "suggested") {
    return { background: "#fff7ed", color: "#c2410c", border: "#fdba74", label: "Pending approval" };
  }
  if (event.eventType === "accepted") {
    return { background: "#ecfdf3", color: "#15803d", border: "#bbf7d0", label: "Accepted" };
  }
  return { background: "#eff6ff", color: "#1d4ed8", border: "#bfdbfe", label: "Auto executed" };
}

function getEventOriginLabel(sourceKind?: string | null): string {
  switch (sourceKind) {
    case "meeting":
      return "Meeting transcript";
    case "briefing":
      return "Login briefing";
    case "schedule":
      return "Scheduled scan";
    case "slack":
      return "Slack signal";
    case "email":
      return "Email signal";
    case "calendar":
      return "Calendar signal";
    case "chat":
    case null:
    case undefined:
      return "Larry chat";
    default:
      return formatStatus(sourceKind);
  }
}

function getMemorySourceLabel(sourceKind?: string | null): string {
  switch (sourceKind) {
    case "chat":
      return "Larry chat";
    case "action":
      return "Accepted action";
    case "meeting":
      return "Meeting";
    case "slack":
      return "Slack";
    case "email":
      return "Email";
    case "calendar":
      return "Calendar";
    case "briefing":
      return "Briefing";
    case "schedule":
      return "Schedule";
    default:
      return sourceKind?.trim() ? formatStatus(sourceKind) : "General";
  }
}

function getEventSourceMeta(sourceKind?: string | null): string {
  switch (sourceKind) {
    case "meeting":
      return "Captured from meeting transcript";
    case "briefing":
      return "Generated during login briefing";
    case "schedule":
      return "Generated by scheduled scan";
    case "slack":
      return "Generated from Slack signal";
    case "email":
      return "Generated from email signal";
    case "calendar":
      return "Generated from calendar signal";
    case "chat":
    case null:
    case undefined:
      return "Requested from Larry chat";
    default:
      return `Generated from ${formatStatus(sourceKind)}`;
  }
}

function getEventMeta(event: WorkspaceLarryEvent): string {
  const pieces = [
    formatStatus(event.actionType),
    event.requestedByName ? `Requested by ${event.requestedByName}` : getEventSourceMeta(event.sourceKind),
  ];

  if (event.eventType === "accepted" && event.approvedByName) {
    pieces.push(`Accepted by ${event.approvedByName}`);
  } else if (event.executionMode === "auto") {
    pieces.push("Executed by Larry");
  } else if (event.executedByName) {
    pieces.push(`Executed by ${event.executedByName}`);
  }

  return pieces.join(" · ");
}

const MEMORY_FILTERS: Array<{ value: string; label: string }> = [
  { value: "all", label: "All sources" },
  { value: "chat", label: "Chat turns" },
  { value: "action", label: "Accepted actions" },
  { value: "meeting", label: "Meetings" },
  { value: "slack", label: "Slack" },
  { value: "email", label: "Email" },
  { value: "calendar", label: "Calendar" },
];

function getMemoryMeta(entry: WorkspaceProjectMemoryEntry): string {
  const pieces = [getMemorySourceLabel(entry.sourceKind)];
  if (entry.source?.trim()) {
    pieces.push(entry.source.trim());
  }
  return pieces.join(" - ");
}

export function ProjectWorkspaceView({ projectId }: { projectId: string }) {
  const chrome = useWorkspaceChrome();
  const [memorySourceFilter, setMemorySourceFilter] = useState("all");
  const activeMemorySource = memorySourceFilter === "all" ? null : memorySourceFilter;
  const { project, tasks, health, meetings, outcomes, timeline, loading, error, refresh } = useProjectData(projectId);
  const {
    suggested,
    activity,
    conversations,
    loading: actionCentreLoading,
    error: actionCentreError,
    accepting,
    dismissing,
    accept,
    dismiss,
    refresh: refreshActionCentre,
  } = useProjectActionCentre(projectId, refresh);
  const {
    entries: memoryEntries,
    loading: memoryLoading,
    error: memoryError,
    refresh: refreshMemory,
  } = useProjectMemory(projectId, activeMemorySource);

  const completionRate = useMemo(() => {
    if (health?.completionRate != null) return Number(health.completionRate);
    if (tasks.length === 0) return 0;
    const completed = tasks.filter((task) => task.status === "completed").length;
    return (completed / tasks.length) * 100;
  }, [health?.completionRate, tasks]);

  const openTasks = tasks.filter((task) => task.status !== "completed").length;
  const blockedTasks = tasks.filter((task) => task.status === "blocked").length;
  const recentTasks = (timeline?.gantt ?? tasks).slice(0, 6);
  const riskTone = getRiskTone(project?.riskLevel ?? health?.riskLevel ?? "low");

  function openLarry() {
    chrome?.openLarry();
  }

  function openConversation(conversationId: string) {
    chrome?.openLarry();
    window.dispatchEvent(new CustomEvent("larry:load-conversation", { detail: conversationId }));
  }

  function startProjectChat() {
    chrome?.openLarry();
    window.dispatchEvent(
      new CustomEvent("larry:prefill", {
        detail: "Review this project and suggest the next actions worth taking.",
      }),
    );
  }

  if (loading && !project) {
    return (
      <div className="flex min-h-0 flex-1 items-center justify-center">
        <div className="h-5 w-5 animate-spin rounded-full border-2 border-[var(--color-brand)] border-t-transparent" />
      </div>
    );
  }

  if (!project) {
    return (
      <div className="min-h-0 flex-1 overflow-y-auto" style={{ background: "var(--page-bg)" }}>
        <div className="mx-auto max-w-[1100px] px-6 py-8">
          <div
            style={{
              borderRadius: "var(--radius-card)",
              border: "1px solid var(--border)",
              background: "var(--surface)",
              padding: "24px",
            }}
          >
            <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
              Project unavailable
            </p>
            <p className="mt-2 text-[14px]" style={{ color: "var(--text-2)" }}>
              {error ?? "This project could not be found on the new workspace data path."}
            </p>
            <Link href="/workspace" className="mt-5 inline-flex items-center gap-2 text-[14px] font-semibold" style={{ color: "var(--cta)" }}>
              Back to workspace
              <ArrowRight size={14} />
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-0 flex-1 overflow-y-auto" style={{ background: "var(--page-bg)" }}>
      <div className="mx-auto max-w-[1200px] space-y-6 px-6 py-8">
        <section
          style={{
            borderRadius: "var(--radius-card)",
            border: "1px solid var(--border)",
            background: "var(--surface)",
            padding: "24px",
          }}
        >
          <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
            <div className="min-w-0 flex-1">
              <div className="flex flex-wrap items-center gap-2">
                <span
                  className="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[12px] font-semibold"
                  style={{
                    background: riskTone.background,
                    color: riskTone.color,
                    borderColor: riskTone.border,
                  }}
                >
                  <CircleAlert size={14} />
                  {formatStatus(project.riskLevel ?? health?.riskLevel ?? "low risk")}
                </span>
                <span
                  className="inline-flex items-center rounded-full border px-3 py-1 text-[12px] font-medium"
                  style={{
                    background: "var(--surface-2)",
                    color: "var(--text-2)",
                    borderColor: "var(--border)",
                  }}
                >
                  {formatStatus(project.status)}
                </span>
              </div>
              <h1 className="mt-4 text-[28px] font-semibold tracking-[-0.04em]" style={{ color: "var(--text-1)" }}>
                {project.name}
              </h1>
              <p className="mt-3 max-w-[760px] text-[15px] leading-7" style={{ color: "var(--text-2)" }}>
                {project.description?.trim() || "This workspace is now running on the scoped Phase 1 project overview contract."}
              </p>
              <div className="mt-4 flex flex-wrap items-center gap-4 text-[13px]" style={{ color: "var(--text-muted)" }}>
                <span className="inline-flex items-center gap-2">
                  <CalendarDays size={14} />
                  Target {formatDate(project.targetDate)}
                </span>
                <span className="inline-flex items-center gap-2">
                  <Clock3 size={14} />
                  Updated {formatRelativeTime(project.updatedAt)}
                </span>
                <span className="inline-flex items-center gap-2">
                  <FolderKanban size={14} />
                  {tasks.length} tracked tasks
                </span>
              </div>
            </div>
            <div className="flex flex-wrap gap-3">
              <button
                type="button"
                onClick={startProjectChat}
                className="inline-flex h-10 items-center gap-2 rounded-full px-4 text-[13px] font-semibold text-white"
                style={{ background: "var(--cta)" }}
              >
                <Sparkles size={14} />
                Ask Larry
              </button>
              <Link
                href={`/workspace/chats?projectId=${projectId}`}
                className="inline-flex h-10 items-center gap-2 rounded-full border px-4 text-[13px] font-semibold"
                style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
              >
                <MessageSquare size={14} />
                Full chat history
              </Link>
              <Link
                href={`/workspace/projects/${projectId}/dashboard`}
                className="inline-flex h-10 items-center gap-2 rounded-full border px-4 text-[13px] font-semibold"
                style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
              >
                <Activity size={14} />
                Report view
              </Link>
            </div>
          </div>
        </section>

        <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          {[
            { label: "Completion", value: formatPercent(completionRate), detail: `${openTasks} still open` },
            { label: "Blocked", value: String(blockedTasks), detail: "Tasks needing attention" },
            { label: "Pending Actions", value: String(suggested.length), detail: "Awaiting review" },
            { label: "Recent Meetings", value: String(meetings.length), detail: "Project context inputs" },
          ].map((stat) => (
            <div
              key={stat.label}
              style={{
                borderRadius: "var(--radius-card)",
                border: "1px solid var(--border)",
                background: "var(--surface)",
                padding: "18px 20px",
              }}
            >
              <p className="text-[12px] font-semibold uppercase tracking-[0.14em]" style={{ color: "var(--text-muted)" }}>
                {stat.label}
              </p>
              <p className="mt-3 text-[28px] font-semibold tracking-[-0.04em]" style={{ color: "var(--text-1)" }}>
                {stat.value}
              </p>
              <p className="mt-2 text-[13px]" style={{ color: "var(--text-2)" }}>
                {stat.detail}
              </p>
            </div>
          ))}
        </section>

        <section className="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(360px,1fr)]">
          <div className="space-y-6">
            <CollaboratorsPanel projectId={projectId} />

            <div
              style={{
                borderRadius: "var(--radius-card)",
                border: "1px solid var(--border)",
                background: "var(--surface)",
                padding: "20px",
              }}
            >
              <div className="flex items-center justify-between gap-4">
                <div>
                  <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                    Project Context
                  </p>
                  <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                    Stable workspace-native project summary and context feed.
                  </p>
                </div>
              </div>
              <div className="mt-5 grid gap-4 md:grid-cols-2">
                <div
                  style={{
                    borderRadius: "var(--radius-btn)",
                    border: "1px solid var(--border)",
                    background: "var(--surface-2)",
                    padding: "16px",
                  }}
                >
                  <p className="text-[12px] font-semibold uppercase tracking-[0.12em]" style={{ color: "var(--text-muted)" }}>
                    Health Summary
                  </p>
                  <p className="mt-3 text-[14px] leading-7" style={{ color: "var(--text-2)" }}>
                    Completion {formatPercent(health?.completionRate ?? completionRate)} with {blockedTasks} blocked tasks and average risk score {Math.round(health?.avgRiskScore ?? 0)}.
                  </p>
                </div>
                <div
                  style={{
                    borderRadius: "var(--radius-btn)",
                    border: "1px solid var(--border)",
                    background: "var(--surface-2)",
                    padding: "16px",
                  }}
                >
                  <p className="text-[12px] font-semibold uppercase tracking-[0.12em]" style={{ color: "var(--text-muted)" }}>
                    Larry Narrative
                  </p>
                  <p className="mt-3 text-[14px] leading-7" style={{ color: "var(--text-2)" }}>
                    {outcomes?.narrative?.trim() || "Larry narrative will deepen here as we consolidate project memory and action provenance in later phases."}
                  </p>
                </div>
              </div>
            </div>

            <div
              style={{
                borderRadius: "var(--radius-card)",
                border: "1px solid var(--border)",
                background: "var(--surface)",
                padding: "20px",
              }}
            >
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                  <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                    Project Context Timeline
                  </p>
                  <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                    Durable memory from chat, accepted actions, and worker-processed meeting/email/slack/calendar signals.
                  </p>
                </div>
                <label className="text-[12px] font-semibold" style={{ color: "var(--text-muted)" }}>
                  Source
                  <select
                    value={memorySourceFilter}
                    onChange={(event) => setMemorySourceFilter(event.target.value)}
                    className="ml-2 rounded-full border px-3 py-1.5 text-[12px] font-medium"
                    style={{ borderColor: "var(--border)", background: "var(--surface-2)", color: "var(--text-1)" }}
                  >
                    {MEMORY_FILTERS.map((filter) => (
                      <option key={filter.value} value={filter.value}>
                        {filter.label}
                      </option>
                    ))}
                  </select>
                </label>
              </div>

              <div className="mt-5 space-y-3">
                {memoryError && (
                  <div
                    className="rounded-[18px] border px-4 py-3 text-[13px]"
                    style={{ borderColor: "#fecaca", background: "#fef2f2", color: "#b91c1c" }}
                  >
                    {memoryError}
                  </div>
                )}
                {memoryLoading && memoryEntries.length === 0 ? (
                  <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                    Loading project memory...
                  </p>
                ) : memoryEntries.length === 0 ? (
                  <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                    No memory entries yet for this source filter.
                  </p>
                ) : (
                  memoryEntries.map((entry) => (
                    <div
                      key={entry.id}
                      className="rounded-[18px] border px-4 py-3"
                      style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                    >
                      <div className="flex items-start justify-between gap-3">
                        <p className="text-[13px] font-semibold" style={{ color: "var(--text-1)" }}>
                          {getMemoryMeta(entry)}
                        </p>
                        <span className="shrink-0 text-[12px]" style={{ color: "var(--text-muted)" }}>
                          {formatRelativeTime(entry.createdAt)}
                        </span>
                      </div>
                      <p className="mt-2 text-[13px] leading-6" style={{ color: "var(--text-2)" }}>
                        {entry.content}
                      </p>
                    </div>
                  ))
                )}
              </div>
            </div>

            <div
              style={{
                borderRadius: "var(--radius-card)",
                border: "1px solid var(--border)",
                background: "var(--surface)",
                padding: "20px",
              }}
            >
              <div className="flex items-center justify-between gap-4">
                <div>
                  <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                    Active Work
                  </p>
                  <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                    Tasks are now loaded from the project overview route instead of the workspace snapshot.
                  </p>
                </div>
              </div>
              <div className="mt-5 space-y-3">
                {recentTasks.length === 0 ? (
                  <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                    No tasks yet for this project.
                  </p>
                ) : (
                  recentTasks.map((task) => (
                    <div
                      key={task.id}
                      className="flex items-start justify-between gap-4 rounded-[18px] border px-4 py-3"
                      style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                    >
                      <div className="min-w-0 flex-1">
                        <p className="truncate text-[14px] font-semibold" style={{ color: "var(--text-1)" }}>
                          {task.title}
                        </p>
                        <p className="mt-1 text-[12px]" style={{ color: "var(--text-muted)" }}>
                          {formatStatus(task.status)} · Due {formatDate(task.dueDate)}
                        </p>
                      </div>
                      <span
                        className="shrink-0 rounded-full border px-2.5 py-1 text-[11px] font-semibold"
                        style={{ borderColor: "var(--border)", color: "var(--text-2)", background: "var(--surface)" }}
                      >
                        {formatStatus(task.priority)}
                      </span>
                    </div>
                  ))
                )}
              </div>
            </div>

            <div
              style={{
                borderRadius: "var(--radius-card)",
                border: "1px solid var(--border)",
                background: "var(--surface)",
                padding: "20px",
              }}
            >
              <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                Recent Meetings
              </p>
              <div className="mt-5 space-y-3">
                {meetings.length === 0 ? (
                  <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                    No meetings linked to this project yet.
                  </p>
                ) : (
                  meetings.slice(0, 4).map((meeting) => (
                    <div
                      key={meeting.id}
                      className="rounded-[18px] border px-4 py-3"
                      style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                    >
                      <div className="flex items-center justify-between gap-4">
                        <p className="truncate text-[14px] font-semibold" style={{ color: "var(--text-1)" }}>
                          {meeting.title?.trim() || "Untitled meeting"}
                        </p>
                        <span className="shrink-0 text-[12px]" style={{ color: "var(--text-muted)" }}>
                          {formatDate(meeting.meetingDate ?? meeting.createdAt)}
                        </span>
                      </div>
                      <p className="mt-2 line-clamp-2 text-[13px] leading-6" style={{ color: "var(--text-2)" }}>
                        {meeting.summary?.trim() || `${meeting.actionCount} extracted action${meeting.actionCount === 1 ? "" : "s"}.`}
                      </p>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>

          <div className="space-y-6">
            <div
              style={{
                borderRadius: "var(--radius-card)",
                border: "1px solid var(--border)",
                background: "var(--surface)",
                padding: "20px",
              }}
            >
              <div className="flex items-center justify-between gap-4">
                <div>
                  <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                    Action Centre
                  </p>
                  <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                    Project-scoped Larry actions and conversations now load from one action-centre contract.
                  </p>
                </div>
                <button
                  type="button"
                  onClick={() => {
                    void Promise.all([refresh(), refreshActionCentre(), refreshMemory()]);
                  }}
                  className="text-[12px] font-semibold"
                  style={{ color: "var(--cta)" }}
                >
                  Refresh
                </button>
              </div>

              <div className="mt-5 space-y-4">
                <div>
                  <p className="text-[12px] font-semibold uppercase tracking-[0.12em]" style={{ color: "var(--text-muted)" }}>
                    Pending review
                  </p>
                  <div className="mt-3 space-y-3">
                    {actionCentreLoading && suggested.length === 0 ? (
                      <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                        Loading suggested actions...
                      </p>
                    ) : suggested.length === 0 ? (
                      <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                        No pending Larry actions for this project.
                      </p>
                    ) : (
                      suggested.map((event) => (
                        <div
                          key={event.id}
                          className="rounded-[18px] border px-4 py-4"
                          style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                        >
                          <div className="flex items-start justify-between gap-4">
                            <div className="min-w-0 flex-1">
                              <p className="text-[14px] font-semibold" style={{ color: "var(--text-1)" }}>
                                {event.displayText}
                              </p>
                              <p className="mt-2 text-[13px] leading-6" style={{ color: "var(--text-2)" }}>
                                {event.reasoning || "Larry proposed this action from current project context."}
                              </p>
                            </div>
                            <span
                              className="shrink-0 rounded-full border px-2.5 py-1 text-[11px] font-semibold"
                              style={{
                                background: getEventTone(event).background,
                                color: getEventTone(event).color,
                                borderColor: getEventTone(event).border,
                              }}
                            >
                              {getEventTone(event).label}
                            </span>
                          </div>
                          <p className="mt-3 text-[12px]" style={{ color: "var(--text-muted)" }}>
                            {getEventMeta(event)} · {formatRelativeTime(event.createdAt)}
                          </p>
                          {(event.responseMessagePreview || event.requestMessagePreview) && (
                            <p className="mt-2 rounded-[14px] border px-3 py-2 text-[12px] leading-5" style={{ borderColor: "var(--border)", background: "var(--surface)" }}>
                              {(event.responseMessagePreview ?? event.requestMessagePreview)?.trim()}
                            </p>
                          )}
                          <div className="mt-3 flex flex-wrap items-center justify-between gap-3">
                            {event.conversationId ? (
                              <button
                                type="button"
                                onClick={() => openConversation(event.conversationId!)}
                                className="text-[12px] font-semibold"
                                style={{ color: "var(--cta)" }}
                              >
                                Open linked chat
                              </button>
                            ) : (
                              <span className="text-[12px]" style={{ color: "var(--text-muted)" }}>
                                Origin: {getEventOriginLabel(event.sourceKind)}
                              </span>
                            )}
                            <div className="flex items-center gap-2">
                              <button
                                type="button"
                                onClick={() => void dismiss(event.id)}
                                disabled={dismissing === event.id}
                                className="rounded-full border px-3 py-1.5 text-[12px] font-semibold"
                                style={{ borderColor: "var(--border)", color: "var(--text-2)" }}
                              >
                                {dismissing === event.id ? "Dismissing..." : "Dismiss"}
                              </button>
                              <button
                                type="button"
                                onClick={() => void accept(event.id)}
                                disabled={accepting === event.id}
                                className="rounded-full px-3 py-1.5 text-[12px] font-semibold text-white"
                                style={{ background: "var(--cta)" }}
                              >
                                {accepting === event.id ? "Accepting..." : "Accept"}
                              </button>
                            </div>
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                </div>

                <div>
                  <p className="text-[12px] font-semibold uppercase tracking-[0.12em]" style={{ color: "var(--text-muted)" }}>
                    Recent activity
                  </p>
                  <div className="mt-3 space-y-3">
                    {activity.length === 0 ? (
                      <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                        No recent Larry activity logged yet.
                      </p>
                    ) : (
                      activity.map((event) => (
                        <div key={event.id} className="rounded-[18px] border px-4 py-3" style={{ borderColor: "var(--border)" }}>
                          <div className="flex items-start gap-3">
                            <CheckCircle2 size={16} className="mt-0.5 shrink-0" style={{ color: "var(--cta)" }} />
                            <div className="min-w-0 flex-1">
                              <div className="flex items-start justify-between gap-3">
                                <p className="text-[13px] font-semibold" style={{ color: "var(--text-1)" }}>
                                  {event.displayText}
                                </p>
                                <span
                                  className="shrink-0 rounded-full border px-2.5 py-1 text-[11px] font-semibold"
                                  style={{
                                    background: getEventTone(event).background,
                                    color: getEventTone(event).color,
                                    borderColor: getEventTone(event).border,
                                  }}
                                >
                                  {getEventTone(event).label}
                                </span>
                              </div>
                              <p className="mt-1 text-[12px]" style={{ color: "var(--text-muted)" }}>
                                {getEventMeta(event)} · {formatRelativeTime(event.executedAt ?? event.createdAt)}
                              </p>
                              {event.responseMessagePreview && (
                                <p className="mt-2 line-clamp-2 text-[12px] leading-5" style={{ color: "var(--text-2)" }}>
                                  {event.responseMessagePreview}
                                </p>
                              )}
                              {event.conversationId && (
                                <button
                                  type="button"
                                  onClick={() => openConversation(event.conversationId!)}
                                  className="mt-2 text-[12px] font-semibold"
                                  style={{ color: "var(--cta)" }}
                                >
                                  Jump to chat
                                </button>
                              )}
                            </div>
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                </div>
              </div>
            </div>

            <div
              style={{
                borderRadius: "var(--radius-card)",
                border: "1px solid var(--border)",
                background: "var(--surface)",
                padding: "20px",
              }}
            >
              <div className="flex items-center justify-between gap-4">
                <div>
                  <p className="text-[18px] font-semibold" style={{ color: "var(--text-1)" }}>
                    Project Larry Chat
                  </p>
                  <p className="mt-1 text-[13px]" style={{ color: "var(--text-2)" }}>
                    Stable slot for project-specific conversations and history.
                  </p>
                </div>
                <button type="button" onClick={openLarry} className="text-[12px] font-semibold" style={{ color: "var(--cta)" }}>
                  Open panel
                </button>
              </div>

              <div className="mt-5 space-y-3">
                {actionCentreError && (
                  <div className="rounded-[18px] border px-4 py-3 text-[13px]" style={{ borderColor: "#fecaca", background: "#fef2f2", color: "#b91c1c" }}>
                    {actionCentreError}
                  </div>
                )}
                {actionCentreLoading && conversations.length === 0 ? (
                  <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
                    Loading conversation history...
                  </p>
                ) : conversations.length === 0 ? (
                  <div className="rounded-[18px] border border-dashed px-4 py-6 text-center" style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}>
                    <p className="text-[14px] font-semibold" style={{ color: "var(--text-1)" }}>
                      No project chats yet
                    </p>
                    <p className="mt-2 text-[13px] leading-6" style={{ color: "var(--text-2)" }}>
                      Start the first project-specific conversation to give this workspace its own Larry history.
                    </p>
                    <button
                      type="button"
                      onClick={startProjectChat}
                      className="mt-4 inline-flex h-10 items-center gap-2 rounded-full px-4 text-[13px] font-semibold text-white"
                      style={{ background: "var(--cta)" }}
                    >
                      <Sparkles size={14} />
                      Start project chat
                    </button>
                  </div>
                ) : (
                  conversations.map((conversation) => (
                    <button
                      key={conversation.id}
                      type="button"
                      onClick={() => openConversation(conversation.id)}
                      className="flex w-full items-start gap-3 rounded-[18px] border px-4 py-3 text-left"
                      style={{ borderColor: "var(--border)", background: "var(--surface-2)" }}
                    >
                      <MessageSquare size={16} className="mt-0.5 shrink-0" style={{ color: "var(--cta)" }} />
                      <div className="min-w-0 flex-1">
                        <p className="truncate text-[13px] font-semibold" style={{ color: "var(--text-1)" }}>
                          {getConversationTitle(conversation)}
                        </p>
                        <p className="mt-1 line-clamp-2 text-[12px] leading-5" style={{ color: "var(--text-2)" }}>
                          {conversation.lastMessagePreview?.trim() || "No messages saved yet."}
                        </p>
                      </div>
                      <span className="shrink-0 text-[12px]" style={{ color: "var(--text-muted)" }}>
                        {formatRelativeTime(conversation.lastMessageAt ?? conversation.updatedAt)}
                      </span>
                    </button>
                  ))
                )}
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
